import { Data } from "../deps.js";
export declare const Credential: any;
export declare type Credential = Data.Static<typeof Credential>;
export declare const Address: any;
export declare type Address = Data.Static<typeof Address>;
export declare const Value: any;
export declare type Value = Data.Static<typeof Value>;
export declare const BidOption: any;
export declare type BidOption = Data.Static<typeof BidOption>;
export declare const OutRef: any;
export declare type OutRef = Data.Static<typeof OutRef>;
export declare const ListingDetails: any;
export declare type ListingDetails = Data.Static<typeof ListingDetails>;
export declare const BiddingDetails: any;
export declare type BiddingDetails = Data.Static<typeof BiddingDetails>;
export declare const RoyaltyRecipient: any;
export declare type RoyaltyRecipient = Data.Static<typeof RoyaltyRecipient>;
export declare const RoyaltyInfo: any;
export declare type RoyaltyInfo = Data.Static<typeof RoyaltyInfo>;
export declare const RoyaltyToken: any;
export declare type RoyaltyToken = Data.Static<typeof RoyaltyToken>;
export declare const PaymentDatum: any;
export declare type PaymentDatum = Data.Static<typeof PaymentDatum>;
export declare const TradeAction: any;
export declare type TradeAction = Data.Static<typeof TradeAction>;
export declare const TradeDatum: any;
export declare type TradeDatum = Data.Static<typeof TradeDatum>;
export declare const TradeParams: any;
export declare type TradeParams = Data.Static<typeof TradeParams>;
